LOST_REASONS = ["Long Sales Cycle", "Missing Features", "No Decision-Maker", "Other", "Poor Fit", "Pricing", "Unresponsive Prospect"]
OTHER_LOST_REASONS = [
    "Budget constraints",
    "Competitor offered better pricing",
    "Timeline doesn't align with requirements",
    "Decision maker changed",
    "Project cancelled or postponed",
    "Went with internal solution",
    "Feature requirements not met",
    "Lack of executive buy-in",
    "Incumbent vendor renewed contract",
    "Technical compatibility issues",
    "Compliance/regulatory concerns",
    "Economic downturn impact",
    "Merger/acquisition changes priorities",
    "Chosen alternative solution",
    "ROI not demonstrated clearly",
    "Implementation complexity too high",
    "Support/service concerns",
    "Integration challenges",
    "No decision made",
    "Lost to status quo",
    "Pricing outside budget range",
    "Vendor credibility concerns",
    "Contract terms disagreement",
    "Security requirements not met",
    "Geographic/location limitations",
    "Seasonal business changes",
    "Key stakeholder left company",
    "Different strategic direction",
    "Proof of concept failed",
    "Reference checks negative",
]
