import random

from faker import Faker
from faker.providers import BaseProvider


US_COLLEGES = [
    "Harvard University",
    "Stanford University",
    "Massachusetts Institute of Technology",
    "University of California, Berkeley",
    "California Institute of Technology",
    "Princeton University",
    "Yale University",
    "Columbia University",
    "University of Chicago",
    "University of Pennsylvania",
    "Duke University",
    "Johns Hopkins University",
    "Northwestern University",
    "University of Michigan, Ann Arbor",
    "Cornell University",
    "University of California, Los Angeles",
    "New York University",
    "University of California, San Diego",
    "University of Wisconsin-Madison",
    "University of Washington",
]

US_BANKS = [
    "JPMorgan Chase",
    "Bank of America",
    "Wells Fargo",
    "Citibank",
    "U.S. Bank",
    "PNC Bank",
    "Truist Bank",
    "Goldman Sachs Bank USA",
    "TD Bank",
    "Capital One",
    "HSBC Bank USA",
    "Fifth Third Bank",
    "Ally Bank",
    "KeyBank",
    "Regions Bank",
    "BMO Harris Bank",
    "Huntington National Bank",
    "Citizens Bank",
    "First Republic Bank",
    "M&T Bank",
]

# US Cities by State
US_CITIES_BY_STATE = {
    "AL": [
        "Birmingham",
        "Montgomery",
        "Mobile",
        "Huntsville",
        "Tuscaloosa",
        "Hoover",
        "Dothan",
        "Auburn",
        "Decatur",
        "Madison",
    ],
    "AK": [
        "Anchorage",
        "Fairbanks",
        "Juneau",
        "Sitka",
        "Ketchikan",
        "Wasilla",
        "Kenai",
        "Kodiak",
        "Bethel",
        "Palmer",
    ],
    "AZ": [
        "Phoenix",
        "Tucson",
        "Mesa",
        "Chandler",
        "Scottsdale",
        "Glendale",
        "Gilbert",
        "Tempe",
        "Peoria",
        "Surprise",
    ],
    "AR": [
        "Little Rock",
        "Fort Smith",
        "Fayetteville",
        "Springdale",
        "Jonesboro",
        "North Little Rock",
        "Conway",
        "Rogers",
        "Pine Bluff",
        "Bentonville",
    ],
    "CA": [
        "Los Angeles",
        "San Diego",
        "San Jose",
        "San Francisco",
        "Fresno",
        "Sacramento",
        "Long Beach",
        "Oakland",
        "Bakersfield",
        "Anaheim",
    ],
    "CO": [
        "Denver",
        "Colorado Springs",
        "Aurora",
        "Fort Collins",
        "Lakewood",
        "Thornton",
        "Arvada",
        "Westminster",
        "Pueblo",
        "Centennial",
    ],
    "CT": [
        "Bridgeport",
        "New Haven",
        "Hartford",
        "Stamford",
        "Waterbury",
        "Norwalk",
        "Danbury",
        "New Britain",
        "West Hartford",
        "Greenwich",
    ],
    "DE": [
        "Wilmington",
        "Dover",
        "Newark",
        "Middletown",
        "Smyrna",
        "Milford",
        "Seaford",
        "Georgetown",
        "Elsmere",
        "New Castle",
    ],
    "FL": [
        "Jacksonville",
        "Miami",
        "Tampa",
        "Orlando",
        "St. Petersburg",
        "Hialeah",
        "Tallahassee",
        "Fort Lauderdale",
        "Port St. Lucie",
        "Cape Coral",
    ],
    "GA": [
        "Atlanta",
        "Columbus",
        "Augusta",
        "Savannah",
        "Athens",
        "Sandy Springs",
        "Roswell",
        "Macon",
        "Johns Creek",
        "Albany",
    ],
    "HI": [
        "Honolulu",
        "Pearl City",
        "Hilo",
        "Kailua",
        "Waipahu",
        "Kaneohe",
        "Mililani Town",
        "Kahului",
        "Ewa Gentry",
        "Mililani Mauka",
    ],
    "ID": [
        "Boise",
        "Meridian",
        "Nampa",
        "Idaho Falls",
        "Pocatello",
        "Caldwell",
        "Coeur d'Alene",
        "Twin Falls",
        "Lewiston",
        "Post Falls",
    ],
    "IL": [
        "Chicago",
        "Aurora",
        "Rockford",
        "Joliet",
        "Naperville",
        "Springfield",
        "Peoria",
        "Elgin",
        "Waukegan",
        "Cicero",
    ],
    "IN": [
        "Indianapolis",
        "Fort Wayne",
        "Evansville",
        "South Bend",
        "Carmel",
        "Fishers",
        "Bloomington",
        "Hammond",
        "Gary",
        "Muncie",
    ],
    "IA": [
        "Des Moines",
        "Cedar Rapids",
        "Davenport",
        "Sioux City",
        "Iowa City",
        "Waterloo",
        "Council Bluffs",
        "Ames",
        "Dubuque",
        "West Des Moines",
    ],
    "KS": [
        "Wichita",
        "Overland Park",
        "Kansas City",
        "Topeka",
        "Olathe",
        "Lawrence",
        "Shawnee",
        "Manhattan",
        "Lenexa",
        "Salina",
    ],
    "KY": [
        "Louisville",
        "Lexington",
        "Bowling Green",
        "Owensboro",
        "Covington",
        "Richmond",
        "Georgetown",
        "Florence",
        "Hopkinsville",
        "Nicholasville",
    ],
    "LA": [
        "New Orleans",
        "Baton Rouge",
        "Shreveport",
        "Lafayette",
        "Lake Charles",
        "Kenner",
        "Bossier City",
        "Monroe",
        "Alexandria",
        "Houma",
    ],
    "ME": [
        "Portland",
        "Lewiston",
        "Bangor",
        "South Portland",
        "Auburn",
        "Biddeford",
        "Sanford",
        "Saco",
        "Augusta",
        "Westbrook",
    ],
    "MD": [
        "Baltimore",
        "Frederick",
        "Rockville",
        "Gaithersburg",
        "Bowie",
        "Hagerstown",
        "Annapolis",
        "College Park",
        "Salisbury",
        "Laurel",
    ],
    "MA": [
        "Boston",
        "Worcester",
        "Springfield",
        "Lowell",
        "Cambridge",
        "New Bedford",
        "Brockton",
        "Quincy",
        "Lynn",
        "Fall River",
    ],
    "MI": [
        "Detroit",
        "Grand Rapids",
        "Warren",
        "Sterling Heights",
        "Lansing",
        "Ann Arbor",
        "Flint",
        "Dearborn",
        "Livonia",
        "Westland",
    ],
    "MN": [
        "Minneapolis",
        "Saint Paul",
        "Rochester",
        "Duluth",
        "Bloomington",
        "Brooklyn Park",
        "Plymouth",
        "Saint Cloud",
        "Eagan",
        "Woodbury",
    ],
    "MS": [
        "Jackson",
        "Gulfport",
        "Southaven",
        "Hattiesburg",
        "Biloxi",
        "Meridian",
        "Tupelo",
        "Greenville",
        "Olive Branch",
        "Horn Lake",
    ],
    "MO": [
        "Kansas City",
        "Saint Louis",
        "Springfield",
        "Independence",
        "Columbia",
        "Lee's Summit",
        "O'Fallon",
        "St. Joseph",
        "St. Charles",
        "St. Peters",
    ],
    "MT": [
        "Billings",
        "Missoula",
        "Great Falls",
        "Bozeman",
        "Butte",
        "Helena",
        "Kalispell",
        "Havre",
        "Anaconda",
        "Miles City",
    ],
    "NE": [
        "Omaha",
        "Lincoln",
        "Bellevue",
        "Grand Island",
        "Kearney",
        "Fremont",
        "Hastings",
        "North Platte",
        "Norfolk",
        "Columbus",
    ],
    "NV": [
        "Las Vegas",
        "Henderson",
        "Reno",
        "North Las Vegas",
        "Sparks",
        "Carson City",
        "Fernley",
        "Elko",
        "Mesquite",
        "Boulder City",
    ],
    "NH": [
        "Manchester",
        "Nashua",
        "Concord",
        "Derry",
        "Dover",
        "Rochester",
        "Salem",
        "Merrimack",
        "Hudson",
        "Londonderry",
    ],
    "NJ": [
        "Newark",
        "Jersey City",
        "Paterson",
        "Elizabeth",
        "Edison",
        "Woodbridge",
        "Lakewood",
        "Toms River",
        "Hamilton",
        "Trenton",
    ],
    "NM": [
        "Albuquerque",
        "Las Cruces",
        "Rio Rancho",
        "Santa Fe",
        "Roswell",
        "Farmington",
        "Clovis",
        "Hobbs",
        "Alamogordo",
        "Carlsbad",
    ],
    "NY": [
        "New York City",
        "Buffalo",
        "Rochester",
        "Yonkers",
        "Syracuse",
        "Albany",
        "New Rochelle",
        "Mount Vernon",
        "Schenectady",
        "Utica",
    ],
    "NC": [
        "Charlotte",
        "Raleigh",
        "Greensboro",
        "Durham",
        "Winston-Salem",
        "Fayetteville",
        "Cary",
        "Wilmington",
        "High Point",
        "Concord",
    ],
    "ND": [
        "Fargo",
        "Bismarck",
        "Grand Forks",
        "Minot",
        "West Fargo",
        "Williston",
        "Wahpeton",
        "Dickinson",
        "Jamestown",
        "Mandan",
    ],
    "OH": [
        "Columbus",
        "Cleveland",
        "Cincinnati",
        "Toledo",
        "Akron",
        "Dayton",
        "Parma",
        "Canton",
        "Youngstown",
        "Lorain",
    ],
    "OK": [
        "Oklahoma City",
        "Tulsa",
        "Norman",
        "Broken Arrow",
        "Lawton",
        "Edmond",
        "Moore",
        "Midwest City",
        "Enid",
        "Stillwater",
    ],
    "OR": [
        "Portland",
        "Eugene",
        "Salem",
        "Gresham",
        "Hillsboro",
        "Bend",
        "Beaverton",
        "Medford",
        "Springfield",
        "Corvallis",
    ],
    "PA": [
        "Philadelphia",
        "Pittsburgh",
        "Allentown",
        "Erie",
        "Reading",
        "Scranton",
        "Bethlehem",
        "Lancaster",
        "Harrisburg",
        "Altoona",
    ],
    "RI": [
        "Providence",
        "Warwick",
        "Cranston",
        "Pawtucket",
        "East Providence",
        "Woonsocket",
        "Newport",
        "Central Falls",
        "Westerly",
        "Portsmouth",
    ],
    "SC": [
        "Columbia",
        "Charleston",
        "North Charleston",
        "Mount Pleasant",
        "Rock Hill",
        "Greenville",
        "Summerville",
        "Sumter",
        "Goose Creek",
        "Hilton Head Island",
    ],
    "SD": [
        "Sioux Falls",
        "Rapid City",
        "Aberdeen",
        "Brookings",
        "Watertown",
        "Mitchell",
        "Yankton",
        "Pierre",
        "Huron",
        "Vermillion",
    ],
    "TN": [
        "Nashville",
        "Memphis",
        "Knoxville",
        "Chattanooga",
        "Clarksville",
        "Murfreesboro",
        "Franklin",
        "Johnson City",
        "Bartlett",
        "Hendersonville",
    ],
    "TX": [
        "Houston",
        "San Antonio",
        "Dallas",
        "Austin",
        "Fort Worth",
        "El Paso",
        "Arlington",
        "Corpus Christi",
        "Plano",
        "Laredo",
    ],
    "UT": [
        "Salt Lake City",
        "West Valley City",
        "Provo",
        "West Jordan",
        "Orem",
        "Sandy",
        "Ogden",
        "St. George",
        "Layton",
        "Taylorsville",
    ],
    "VT": [
        "Burlington",
        "Essex",
        "South Burlington",
        "Colchester",
        "Rutland",
        "Bennington",
        "Brattleboro",
        "Milton",
        "Hartford",
        "Williston",
    ],
    "VA": [
        "Virginia Beach",
        "Norfolk",
        "Chesapeake",
        "Richmond",
        "Newport News",
        "Alexandria",
        "Hampton",
        "Portsmouth",
        "Suffolk",
        "Roanoke",
    ],
    "WA": [
        "Seattle",
        "Spokane",
        "Tacoma",
        "Vancouver",
        "Bellevue",
        "Kent",
        "Everett",
        "Renton",
        "Spokane Valley",
        "Federal Way",
    ],
    "WV": [
        "Charleston",
        "Huntington",
        "Morgantown",
        "Parkersburg",
        "Wheeling",
        "Martinsburg",
        "Fairmont",
        "Beckley",
        "Clarksburg",
        "Lewisburg",
    ],
    "WI": [
        "Milwaukee",
        "Madison",
        "Green Bay",
        "Kenosha",
        "Racine",
        "Appleton",
        "Waukesha",
        "Eau Claire",
        "Oshkosh",
        "Janesville",
    ],
    "WY": [
        "Cheyenne",
        "Casper",
        "Laramie",
        "Gillette",
        "Rock Springs",
        "Sheridan",
        "Green River",
        "Evanston",
        "Riverton",
        "Jackson",
    ],
}

CONSUMER_GOODS_FIELDS = [
    "Supply Chain Management",
    "Logistics and Transportation",
    "Industrial Engineering",
    "Manufacturing Engineering",
    "Food Science and Technology",
    "Packaging Science",
    "Quality Assurance/Quality Control",
    "Consumer Behavior",
    "Retail Management",
    "Marketing",
    "Product Design and Development",
    "Chemical Engineering",
    "Business Administration",
    "Operations Management",
    "Environmental Science",
    "Textile Engineering",
    "Sales and Merchandising",
    "International Business",
    "Human Resource Management",
    "Finance and Accounting",
]


def city_by_state(state_abbr=None):
    """Generate a fake city name by US state abbreviation.

    Args:
        state_abbr (str, optional): Two-letter state abbreviation (e.g., 'CA', 'NY').
                                  If None, returns a random city from a random state.

    Returns:
        str: A city name from the specified state.
    """
    if state_abbr is None:
        # Return a random city from a random state
        state_abbr = random.choice(list(US_CITIES_BY_STATE.keys()))

    state_abbr = state_abbr.upper()
    if state_abbr not in US_CITIES_BY_STATE:
        return city_by_state()

    return random.choice(US_CITIES_BY_STATE[state_abbr])


class CustomContact(BaseProvider):
    def contact(self):
        first_name = faker.first_name()
        last_name = faker.last_name()
        full_name = f"{first_name} {last_name}"
        email = f"{first_name.lower()}_{last_name.lower()}@deeptune.ai"
        private_email = f"{first_name.lower()}_{faker.random_int(min=1000, max=9999)}@gmail.com"
        birthday = faker.date_of_birth(minimum_age=18, maximum_age=65)
        # Generate a phone number in the format '+1 212 555 4567'
        country_code = "+1"
        area_code = faker.random_int(min=200, max=999)
        exchange_code = faker.random_int(min=100, max=999)
        subscriber_number = faker.random_int(min=1000, max=9999)
        phone = f"{country_code} {area_code} {exchange_code} {subscriber_number}"

        # Generate city and state pair for consistency
        city_state = self.random_city_state_pair()

        address = {
            "street": faker.street_address(),
            "street2": faker.secondary_address(),
            "city": city_state["city"],
            "state": city_state["state"],
            "zip": faker.zipcode(),
            "country": "US",
        }
        visa_no = "".join(random.choices("ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789", k=8))
        work_permit_no = "".join(random.choices("ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789", k=9))
        visa_expiration_date = faker.date_between(start_date="+1y", end_date="+5y").strftime("%Y-%m-%d")
        work_permit_expiration_date = faker.date_between(start_date="+1y", end_date="+5y").strftime("%Y-%m-%d")
        return {
            "full_name": full_name,
            "email": email,
            "private_email": private_email,
            "birthday": birthday,
            "phone": phone,
            "address": address,
            "city": city_state["city"],
            "school": random.choice(US_COLLEGES),
            "visa_no": visa_no,
            "work_permit_no": work_permit_no,
            "visa_expiration_date": visa_expiration_date,
            "work_permit_expiration_date": work_permit_expiration_date,
            "bank_name": random.choice(US_BANKS),
            "field_of_study": random.choice(CONSUMER_GOODS_FIELDS),
        }


faker = Faker()
faker.add_provider(CustomContact)
